### ISSUE TITLE
Authentication issues, 401 unauthorized.

### ISSUE THREAD

**Issue by MrTemple** [veteranbv/unifi-client-updater#1]
I've been trying to get this to work with my UDM SE (v3.2.12) to compare to a similar tool I'm developing in Swift. I just can't get your script to authenticate. I keep getting `{"error":{"code":401,"message":"Unauthorized"}}`

Note: It seemed like the update to v3.2.12 yesterday changed authentication a bit for my script. But your script appears to still construct the session correctly.

My Swift code uses the identical values for the CSRF_TOKEN and SESSION_COOKIE. That script can authenticate for requests, get all clients etc. But my tool is failing when I try to update or create a client ip reservation (even a brand new reservation with a non-conflicting name/mac/ip). I keep getting `{"error":{"code":403,"message":"Forbidden"}}`

I was hoping to use your script to compare. It looks like I'm calling the update exactly as you are, but I keep bumping into the authentication issue, so I can't verify if it's me or if Unify has changed something with the most recent update. I've debugged the hell out of your test_api.py script and everything in the session cookies and headers looks identical to my Swift script, which can authenticate.

So I guess a couple questions for you. It your script still authenticating for you? Are you using the same version?

**Comment by veteranbv** [comment]
I went in, started a new session with my Unifi console url, grabbed my updated csrf token and session cookie, updated my .env, and tested my existing scripts without any modifications. Everything authenticated, tested API endpoints, and created and deleted clients. I'm not able to reproduce the issue you described at this time. Let me know if you have more information. Happy to make adjustments and re-open. I really appreciate you using the project and taking a look at this.
